replicas: 1

image:
  repository: lenisha/vsts-agent-infrastructure
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 4Gi
  disk: "50Gi"
