replicas: 1

image:
  repository: lenisha/vsts-agent-infrastructure
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi
  disk: "50Gi"
